/**
 * Map configuration — Everon game-coordinate system.
 *
 * Arma Reforger's Everon is a 12 800 m × 12 800 m world. We map it to a flat
 * virtual degree space so MapLibre can display it without a real-world tile server:
 *
 *   virtual_lng = gameX_metres / METRES_PER_DEGREE
 *   virtual_lat = gameZ_metres / METRES_PER_DEGREE
 *
 * This keeps distances roughly correct (1 virtual degree ≈ 111 km at the equator,
 * so our 12.8 km game world occupies ≈ 0.115 virtual degrees in each axis).
 *
 * GAME MAP IMAGE
 * Place a copy of the Everon map image at:  public/everon-map.jpg
 * The image should have the SW corner at game coords (0, 0) and the NE corner at
 * (GAME_WORLD_SIZE, GAME_WORLD_SIZE).  Community map screenshots work well; for
 * best quality export a top-down render from the Workbench or use a community tile.
 */

export const GAME_WORLD_SIZE = 12_800 // metres — Everon map edge length (12.8 km × 12.8 km)
export const METRES_PER_DEGREE = 111_320

/** Convert Arma Reforger game-world metres to virtual lng/lat for MapLibre. */
export function gameToCoords(gameX: number, gameZ: number): { lng: number; lat: number } {
  return {
    lng: gameX / METRES_PER_DEGREE,
    lat: gameZ / METRES_PER_DEGREE,
  }
}

const WORLD_DEG = GAME_WORLD_SIZE / METRES_PER_DEGREE // ≈ 0.11037

const BOUNDS_LNG_MIN = 0
const BOUNDS_LAT_MIN = 0
const BOUNDS_LNG_MAX = WORLD_DEG
const BOUNDS_LAT_MAX = WORLD_DEG

export const MAP_INITIAL_VIEW = {
  longitude: WORLD_DEG / 2,
  latitude: WORLD_DEG / 2,
  zoom: 13,
} as const

export const MAP_BOUNDS = {
  minLng: BOUNDS_LNG_MIN - 0.002,
  maxLng: BOUNDS_LNG_MAX + 0.002,
  minLat: BOUNDS_LAT_MIN - 0.002,
  maxLat: BOUNDS_LAT_MAX + 0.002,
} as const

/**
 * MapLibre raster tile source config for the Everon game map.
 *
 * Tiles are generated by running:  npm run generate-tiles
 * Output: public/tiles/{z}/{x}/{y}.jpg  (standard XYZ Web Mercator scheme)
 *
 * MIN_ZOOM / MAX_ZOOM must match the values in scripts/generate-tiles.py.
 */
export const TILE_SOURCE = {
  tiles: [`${import.meta.env.BASE_URL}tiles/{z}/{x}/{y}.jpg`],
  tileSize: 256,
  minzoom: 10,
  maxzoom: 16,
  bounds: [BOUNDS_LNG_MIN, BOUNDS_LAT_MIN, BOUNDS_LNG_MAX, BOUNDS_LAT_MAX] as [number, number, number, number],
} as const

// Keep for reference / fallback — single-image source used before tile pipeline was set up
export const GAME_MAP_IMAGE_SOURCE = {
  url: `${import.meta.env.BASE_URL}everon-map.jpg`,
  coordinates: [
    [0, WORLD_DEG],
    [WORLD_DEG, WORLD_DEG],
    [WORLD_DEG, 0],
    [0, 0],
  ] as [[number, number], [number, number], [number, number], [number, number]],
} as const
